included: # paths to include during linting. `--path` is ignored if present.
  - VHS
  - VHSTests
disabled_rules: # rule identifiers to exclude from running
  - function_parameter_count
  - nesting
  - todo
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - explicit_init
  - empty_count
  - first_where
  - force_unwrapping
  - generic_type_name
  - implicitly_unwrapped_optional
  - missing_docs
  - sorted_imports
  - switch_case_on_newline
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Frameworks
custom_rules:
  os_log:
    name: "Prefer os_log over print and NSLog"
    regex: "\\b(print|NSLog)\\s*\\("
    match_kinds:
      - identifier
    message: "We prefer the os_log over the print or NSLog methods."
    severity: warning
  dump:
    name: "Dump object contents"
    regex: "\\bdump\\s*\\("
    match_kinds:
      - identifier
    message: "Dumping the object's contents to standard output is not allowed in production."
    severity: warning

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - VHS
    - VCR
identifier_name:
  min_length: # only min_length
    error: 1 # only error
    warning: 1
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
trailing_comma:
  mandatory_comma: true
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
