language: objective-c
osx_image: xcode9
before_install:
  - gem install xcpretty
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --platform "macOS,iOS,tvOS" --no-use-binaries
env:
  matrix:
    - DESTINATION="platform=macOS,arch=x86_64"
    - DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=11.0"
script:
  - swiftlint --strict
  - set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
  - xcodebuild test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -project VHS.xcodeproj -scheme VHS -destination "$DESTINATION" | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'VHS'
